import timeRange from "./timeRange";
import { timeRangeType } from "./timeRange";

export const text_on_screen_keywords = ['CRASH',
                        'COURSE',
                        'Recipe',
                        'three',
                        'bananas',
                        'date',
                        'bunch',
                        'of',
                        'greens',
                        'tbs',
                        'hemp',
                        'seeds',
                        'cups',
                        'water',
                        'of',
                        'the',
                        'cells',
                        'in',
                        'your',
                        'body',
                        'are',
                        'bacterial',
                        'Hearts',
                        'pump',
                        'an',
                        'average',
                        'of',
                        'Litres',
                        'of',
                        'blood',
                        'a',
                        'day',
                        'Lungs',
                        'contain',
                        'over',
                        'million',
                        'capillaries',
                        'You',
                        'have',
                        'approximately',
                        'feet',
                        'of',
                        'intestines',
                        'squished',
                        'into',
                        'your',
                        'belly',
                        'Farts',
                        'smell',
                        'like',
                        'poop',
                        'particles',
                        'Evel',
                        'Knievel',
                        'is',
                        'from',
                        'Montana',
                        'By',
                        'adulthood',
                        'youve',
                        'lost',
                        'of',
                        'your',
                        'bones',
                        'EcoGeek',
                        'headquarters',
                        'You',
                        'have',
                        'over',
                        'muscles',
                        'in',
                        'your',
                        'body',
                        'helmet',
                        'RIDE',
                        'SAFE',
                        'Hank',
                        'normally',
                        'wears',
                        'a',
                        'INTRO',
                        'to',
                        'the',
                        'NERVOUS',
                        'SYSTEM',
                        'NERVOUS',
                        'SYSTEM',
                        'GLIAL',
                        'CELL',
                        'TYPES',
                        'provide',
                        'support',
                        'nutrition',
                        'insulation',
                        'and',
                        'help',
                        'with',
                        'signal',
                        'transmission',
                        'in',
                        'the',
                        'nervous',
                        'system',
                        'form',
                        'myelin',
                        'sheath',
                        'EPENDYMAL',
                        'CELLS',
                        'OLIGODENDROCYTES',
                        'insulate',
                        'help',
                        'form',
                        'line',
                        'cavities',
                        'myelin',
                        'sheath',
                        'wrap',
                        'and',
                        'insulate',
                        'ASTROCYTES',
                        'MICROGLIAL',
                        'CELLS',
                        'SATELLITE',
                        'CELLS',
                        'SCHWANN',
                        'CELLS',
                        'cell',
                        'bodies',
                        'defend',
                        'support',
                        'regulate',
                        'ions',
                        'surround',
                        'neuron',
                        'CENTRAL',
                        'NERVOUS',
                        'SYSTEM',
                        'PERIPHERAL',
                        'NERVOUS',
                        'SYSTEM',
                        'mostly',
                        'unipolar',
                        'efferent',
                        'neurons',
                        'impulse',
                        'moves',
                        'from',
                        'the',
                        'CNS',
                        'to',
                        'the',
                        'rest',
                        'of',
                        'the',
                        'body',
                        'mostly',
                        'mutlipolar',
                        'INTERNEURONS',
                        'association',
                        'neurons',
                        'impulse',
                        'moves',
                        'between',
                        'sensory',
                        'and',
                        'motor',
                        'neurons',
                        'ANATOMY',
                        'PHYSIOLOGY',
                        'GRAPHICS',
                        'TEAM',
                        'Jack',
                        'Kennedy',
                        'Jonathon',
                        'Corbiere',
                        'Kelsey',
                        'Heinrichs',
                        'Nick',
                        'Counter',
                        'Nikkie',
                        'Stinchcombe',
                        'Stephanie',
                        'Bailis',
                        'THOUGHT',
                        'CAFÉ',
                        'Adam',
                        'Winnik',
                        'Cody',
                        'Brown',
                        'Corey',
                        'MacDonald',
                        'James',
                        'Tuer',
                        'Suzanna',
                        'Brusikiewicz',
                        'Tyler',
                        'Sammy',
                        'ACTION',
                        'POTENTIAL',
                        'CREATED',
                        'BY',
                        'GRAPHICS',
                        'INTEGUMENTARY',
                        'LAST',
                        'EPISODE',
                        'NEXT',
                        'EPISODE',
                        'SKIN',
                        'DEEPER',
                        'SUBSCRIBE',
                        'SYSTEM',
                        'part',
                        'Thought',
                        'the']

// Video qPix_X-9t7E
export const timeRangeArr = [
    // new timeRange(68.76, 78.83, timeRangeType.NonDialouge),
    new timeRange(391, 392, timeRangeType.NonDialouge),
    // new timeRange(625.23, 635, timeRangeType.NonDialouge),
    new timeRange(68.0, 78.0, timeRangeType.NoText),
    new timeRange(247.0, 254.0, timeRangeType.NoText),
    new timeRange(249.0, 254.0, timeRangeType.NoText),
    new timeRange(488.0, 511.0, timeRangeType.NoText),
    new timeRange(623.0, 634.0, timeRangeType.NoText),
    new timeRange(625.0, 634.0, timeRangeType.NoText),
  ]
  
  // Video W0TM4LQmoZY
  // const timeRangeArr = [
  //   new timeRange(1.5, 6.37, timeRangeType.NonDialouge),
  //   new timeRange(259.88, 277, timeRangeType.NonDialouge),
  //   new timeRange(4.0, 24.0, timeRangeType.NoText),
  //   new timeRange(46.0, 102.0, timeRangeType.NoText),
  //   new timeRange(176.0, 200.0, timeRangeType.NoText),
  //   new timeRange(227.0, 261.0, timeRangeType.NoText),
  // ]
  
  // Video rNjPI84sApQ
  // const timeRangeArr = [
  //   new timeRange(209.4, 210.89, timeRangeType.NonDialouge),
  //   new timeRange(216.24, 217.27, timeRangeType.NonDialouge),
  //   new timeRange(303.88, 304.96, timeRangeType.NonDialouge),
  //   new timeRange(387.99, 409, timeRangeType.NonDialouge),
  //   new timeRange(6.0, 24.0, timeRangeType.NoText),
  //   new timeRange(59.0, 91.0, timeRangeType.NoText),
  //   new timeRange(162.0, 180.0, timeRangeType.NoText),
  //   new timeRange(322.0, 388.0, timeRangeType.NoText),
  // ]
  
  // Video QVCjdNxJreE
  // const timeRangeArr = [
  //   new timeRange(332.81, 333.91, timeRangeType.NonDialouge),
  //   new timeRange(399.16, 400.20, timeRangeType.NonDialouge),
  //   new timeRange(483.24, 485.18, timeRangeType.NonDialouge),
  //   new timeRange(542.57, 559.00, timeRangeType.NonDialouge),
  //   new timeRange(234.0, 263.0, timeRangeType.NoText),
  //   new timeRange(280.0, 335.0, timeRangeType.NoText),
  //   new timeRange(333.0, 361.0, timeRangeType.NoText),
  // ]
  
  // const timeStampArr1 = [
  //   // low lexical density
  //   [calculatePercentage(45.5, 635), calculatePercentage(57, 635)],
  //   // non-dialouge
  //   [calculatePercentage(68.76, 635), calculatePercentage(78.83, 635)],
  //   // text on screen
  //   [calculatePercentage(247, 635), calculatePercentage(254, 635)],
  //   [calculatePercentage(567, 635), calculatePercentage(571, 635)],
  //   [calculatePercentage(625.23, 635), calculatePercentage(635, 635)],
  // ];
  
  // const timeStampArr2 = [
  //   // non-dialouge
  //   [calculatePercentage(1.5, 277), calculatePercentage(6.37, 277)],
  //   [calculatePercentage(259.88, 277), calculatePercentage(277, 277)],
  //   // low lexical density
  //   // text on screen
  //   [calculatePercentage(4, 277), calculatePercentage(24, 277)],
  //   [calculatePercentage(46, 277), calculatePercentage(102, 277)],
  //   [calculatePercentage(104, 277), calculatePercentage(120, 277)],
  //   [calculatePercentage(176, 277), calculatePercentage(200, 277)],
  //   [calculatePercentage(227, 277), calculatePercentage(276, 277)],
  // ];